#!/bin/bash
echo "Paste these into pxh> after PX4 starts:"
echo "param set COM_RCL_EXCEPT 7"
echo "param set COM_RC_IN_MODE 4"
echo "param set CBRK_FLIGHTTERM 121212"
echo "param set CBRK_SUPPLY_CHK 894281"
echo "param set CBRK_IO_SAFETY 22027"
echo "param set CBRK_USB_CHK 197848"
echo "param set COM_ARM_WO_GPS 1"
echo "param set MAV_0_BROADCAST 1"
echo "param set COM_DISARM_PRFLT 0"
echo "param set GF_ACTION 0"
echo "param set NAV_RCL_ACT 0"
echo "param set COM_PREARM_MODE 0"
echo "param save"
